import type { Metadata } from "next";
import "@/app/globals.css";
import {vazir} from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={vazir.className}
      >
        {children}
      </body>
    </html>
  );
}
